### ISSUE TITLE
AttributeError: np.int

### ISSUE THREAD

**Issue by rychallener** [MartianColonist/POSEIDON#23]
In running through the tutorials I ran into the following error

AttributeError: module 'numpy' has no attribute 'int'.

It looks like np.int was deprecated in v. 1.20 and has since been fully removed. There are several uses of np.int in absorption.py. Replacing them with the built-in `int` (which Numpy claims is safe) seems to solve the problem.

**Comment by MartianColonist** [comment]
Thanks for catching this!

All instances of np.int have been replaced (either with the int method or the np.int64 data type).

POSEIDON has been updated to v1.1.1 to reflect this patch.

**Comment by tonmoydeka** [comment]
Yes, I too had gone through this issue earlier but I did correct it myself.
