### ISSUE TITLE
Typo in transmission_terrestrial tutorial

### ISSUE THREAD

**Issue by cf-q22** [MartianColonist/POSEIDON#3]
Hi,

There's just a small issue in the 4th code cell of the 'transmission_terrestrial' tutorial:

Line 11 and 14 read: chem_species_model

This gives an unexpected keyword argument where I believe the kw should be: chem_species_in_model 

Thanks!

**Comment by MartianColonist** [comment]
Thanks! 

I've fixed this on the dev branch (fff6b473abe3ccc7d661695c5e0c3324d3a18d15), which will be merged with main in the next few days.

**Comment by MartianColonist** [comment]
This issue has been fixed on the main branch (91e83f26c9012f4993c4c6b3285d568ba2d2c800), thanks for your patience.
