### ISSUE TITLE
Problem producing Spectral Contribution plot

### ISSUE THREAD

**Issue by cdfortenbach** [MartianColonist/POSEIDON#31]
I am trying to duplicate the results in your Transmission Spectra Model Visuals (v1.2). Specifically the notebook on the spectral components of a transmission spectrum.  I've stripped the notebook and am just running it directly as a .py file.  There have been some issues that I've bypassed, but I think I am down to one last problem to get it to run.  It seems to be in the plot_spectral_contribution call. 

The error looks like this: 
Opacity pre-interpolation complete.
Traceback (most recent call last):
  File "/media/sf_Win10share/POSEIDON/test0.py", line 147, in <module>
    fig = plot_spectral_contribution(planet, wl, spectrum, spectrum_contribution_list_names, spectrum_contribution_list,
  File "/media/sf_Win10share/POSEIDON/POSEIDON/contributions.py", line 1416, in plot_spectral_contribution
    fig = plot_spectra(spectra, planet, R_to_bin = 100,
  File "/media/sf_Win10share/POSEIDON/POSEIDON/visuals.py", line 1767, in plot_spectra
    for legline in legend.legendHandles:
AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?

Any thoughts on this would be appreciated.  Thanks.

**Comment by MartianColonist** [comment]
This problem arises from newer versions of matplotlib, which changed the attribute 'legendHandles' to 'legend_handles'. 
I'm working on a hotfix for POSEIDON now to fix this (plus another issue with new scipy versions). 

Keep an eye out for POSEIDON v1.2.1 later today!

**Comment by cdfortenbach** [comment]
Thanks very much for your quick response.  I look forward to trying out v1.2.1.    Congrats to your team for completing a number of important/useful upgrades to an already very good analysis code.

**Comment by MartianColonist** [comment]
@cdfortenbach fixed!
